//
// Created by josh on 1/13/16.
// #sqlite3 main.db '.schema'

#ifndef FAVOR_SKYPE_TESTDATA_H_H
#define FAVOR_SKYPE_TESTDATA_H_H

#define SKYPE_ACCOUNT_NAME "ore.sama"
#define SKYPE_CONTACT_1 "fling.it"
#define SKYPE_CONTACT_2 "cutie.pie"

#define SKYPE_SQLITE_SCHEMA "CREATE TABLE DbMeta (key TEXT NOT NULL PRIMARY KEY, value TEXT);"\
"CREATE TABLE AppSchemaVersion (ClientVersion TEXT NOT NULL, SQLiteSchemaVersion INTEGER NOT NULL, SchemaUpdateType INTEGER NOT NULL);"\
"CREATE TABLE Contacts (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, type INTEGER, skypename TEXT, pstnnumber TEXT, aliases TEXT, fullname TEXT, birthday INTEGER, gender INTEGER, languages TEXT, country TEXT, province TEXT, city TEXT, phone_home TEXT, phone_office TEXT, phone_mobile TEXT, emails TEXT, hashed_emails TEXT, homepage TEXT, about TEXT, avatar_image BLOB, mood_text TEXT, rich_mood_text TEXT, timezone INTEGER, capabilities BLOB, profile_timestamp INTEGER, nrof_authed_buddies INTEGER, ipcountry TEXT, avatar_timestamp INTEGER, mood_timestamp INTEGER, received_authrequest TEXT, authreq_timestamp INTEGER, lastonline_timestamp INTEGER, availability INTEGER, displayname TEXT, refreshing INTEGER, given_authlevel INTEGER, given_displayname TEXT, assigned_speeddial TEXT, assigned_comment TEXT, alertstring TEXT, lastused_timestamp INTEGER, authrequest_count INTEGER, assigned_phone1 TEXT, assigned_phone1_label TEXT, assigned_phone2 TEXT, assigned_phone2_label TEXT, assigned_phone3 TEXT, assigned_phone3_label TEXT, buddystatus INTEGER, isauthorized INTEGER, popularity_ord INTEGER, external_id TEXT, external_system_id TEXT, isblocked INTEGER, authorization_certificate BLOB, certificate_send_count INTEGER, account_modification_serial_nr INTEGER, saved_directory_blob BLOB, nr_of_buddies INTEGER, server_synced INTEGER, contactlist_track INTEGER, last_used_networktime INTEGER, authorized_time INTEGER, sent_authrequest TEXT, sent_authrequest_time INTEGER, sent_authrequest_serial INTEGER, buddyblob BLOB, cbl_future BLOB, node_capabilities INTEGER, revoked_auth INTEGER, added_in_shared_group INTEGER, in_shared_group INTEGER, authreq_history BLOB, profile_attachments BLOB, stack_version INTEGER, offline_authreq_id INTEGER, node_capabilities_and INTEGER, authreq_crc INTEGER, authreq_src INTEGER, pop_score INTEGER, authreq_nodeinfo BLOB, main_phone TEXT, unified_servants TEXT, phone_home_normalized TEXT, phone_office_normalized TEXT, phone_mobile_normalized TEXT, sent_authrequest_initmethod INTEGER, authreq_initmethod INTEGER, verified_email BLOB, verified_company BLOB, sent_authrequest_extrasbitmask INTEGER, liveid_cid TEXT, extprop_tags TEXT, extprop_away_since INTEGER);"\
"CREATE TABLE LegacyMessages (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER);"\
"CREATE TABLE Calls (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, begin_timestamp INTEGER, topic TEXT, is_muted INTEGER, is_unseen_missed INTEGER, host_identity TEXT, mike_status INTEGER, duration INTEGER, soundlevel INTEGER, access_token TEXT, active_members INTEGER, is_active INTEGER, name TEXT, video_disabled INTEGER, joined_existing INTEGER, server_identity TEXT, vaa_input_status INTEGER, is_incoming INTEGER, is_conference INTEGER, is_on_hold INTEGER, start_timestamp INTEGER, quality_problems TEXT, current_video_audience TEXT, premium_video_status INTEGER, premium_video_is_grace_period INTEGER, is_premium_video_sponsor INTEGER, premium_video_sponsor_list TEXT, old_members BLOB, partner_handle TEXT, partner_dispname TEXT, type INTEGER, status INTEGER, failurereason INTEGER, failurecode INTEGER, pstn_number TEXT, old_duration INTEGER, conf_participants BLOB, pstn_status TEXT, members BLOB, conv_dbid INTEGER);"\
"CREATE TABLE Accounts (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, status INTEGER, pwdchangestatus INTEGER, logoutreason INTEGER, commitstatus INTEGER, suggested_skypename TEXT, skypeout_balance_currency TEXT, skypeout_balance INTEGER, skypeout_precision INTEGER, skypein_numbers TEXT, subscriptions TEXT, cblsyncstatus INTEGER, offline_callforward TEXT, chat_policy INTEGER, skype_call_policy INTEGER, pstn_call_policy INTEGER, avatar_policy INTEGER, buddycount_policy INTEGER, timezone_policy INTEGER, webpresence_policy INTEGER, phonenumbers_policy INTEGER, voicemail_policy INTEGER, authrequest_policy INTEGER, ad_policy INTEGER, partner_optedout TEXT, service_provider_info TEXT, registration_timestamp INTEGER, nr_of_other_instances INTEGER, partner_channel_status TEXT, flamingo_xmpp_status INTEGER, federated_presence_policy INTEGER, liveid_membername TEXT, roaming_history_enabled INTEGER, cobrand_id INTEGER, owner_under_legal_age INTEGER, type INTEGER, skypename TEXT, pstnnumber TEXT, fullname TEXT, birthday INTEGER, gender INTEGER, languages TEXT, country TEXT, province TEXT, city TEXT, phone_home TEXT, phone_office TEXT, phone_mobile TEXT, emails TEXT, homepage TEXT, about TEXT, profile_timestamp INTEGER, received_authrequest TEXT, displayname TEXT, refreshing INTEGER, given_authlevel INTEGER, aliases TEXT, authreq_timestamp INTEGER, mood_text TEXT, timezone INTEGER, nrof_authed_buddies INTEGER, ipcountry TEXT, given_displayname TEXT, availability INTEGER, lastonline_timestamp INTEGER, capabilities BLOB, avatar_image BLOB, assigned_speeddial TEXT, lastused_timestamp INTEGER, authrequest_count INTEGER, assigned_comment TEXT, alertstring TEXT, avatar_timestamp INTEGER, mood_timestamp INTEGER, rich_mood_text TEXT, synced_email BLOB, set_availability INTEGER, options_change_future BLOB, cbl_profile_blob BLOB, authorized_time INTEGER, sent_authrequest TEXT, sent_authrequest_time INTEGER, sent_authrequest_serial INTEGER, buddyblob BLOB, cbl_future BLOB, node_capabilities INTEGER, node_capabilities_and INTEGER, revoked_auth INTEGER, added_in_shared_group INTEGER, in_shared_group INTEGER, authreq_history BLOB, profile_attachments BLOB, stack_version INTEGER, offline_authreq_id INTEGER, verified_email BLOB, verified_company BLOB, uses_jcs INTEGER);"\
"CREATE TABLE Transfers (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, type INTEGER, partner_handle TEXT, partner_dispname TEXT, status INTEGER, failurereason INTEGER, starttime INTEGER, finishtime INTEGER, filepath TEXT, filename TEXT, filesize TEXT, bytestransferred TEXT, bytespersecond INTEGER, chatmsg_guid BLOB, chatmsg_index INTEGER, convo_id INTEGER, pk_id INTEGER, nodeid BLOB, last_activity INTEGER, flags INTEGER, old_status INTEGER, old_filepath INTEGER, accepttime INTEGER, parent_id INTEGER, offer_send_list TEXT);"\
"CREATE TABLE Voicemails (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, type INTEGER, partner_handle TEXT, partner_dispname TEXT, status INTEGER, failurereason INTEGER, subject TEXT, timestamp INTEGER, duration INTEGER, allowed_duration INTEGER, playback_progress INTEGER, convo_id INTEGER, chatmsg_guid BLOB, notification_id INTEGER, flags INTEGER, size INTEGER, path TEXT, failures INTEGER, vflags INTEGER, xmsg TEXT);"\
"CREATE TABLE Chats (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, name TEXT, options INTEGER, friendlyname TEXT, description TEXT, timestamp INTEGER, activity_timestamp INTEGER, dialog_partner TEXT, adder TEXT, type INTEGER, mystatus INTEGER, myrole INTEGER, posters TEXT, participants TEXT, applicants TEXT, banned_users TEXT, name_text TEXT, topic TEXT, topic_xml TEXT, guidelines TEXT, picture BLOB, alertstring TEXT, is_bookmarked INTEGER, passwordhint TEXT, unconsumed_suppressed_msg INTEGER, unconsumed_normal_msg INTEGER, unconsumed_elevated_msg INTEGER, unconsumed_msg_voice INTEGER, activemembers TEXT, state_data BLOB, lifesigns INTEGER, last_change INTEGER, first_unread_message INTEGER, pk_type INTEGER, dbpath TEXT, split_friendlyname TEXT, conv_dbid INTEGER);"\
"CREATE TABLE Messages (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, convo_id INTEGER, chatname TEXT, author TEXT, from_dispname TEXT, author_was_live INTEGER, guid BLOB, dialog_partner TEXT, timestamp INTEGER, type INTEGER, sending_status INTEGER, consumption_status INTEGER, edited_by TEXT, edited_timestamp INTEGER, param_key INTEGER, param_value INTEGER, body_xml TEXT, identities TEXT, reason TEXT, leavereason INTEGER, participant_count INTEGER, error_code INTEGER, chatmsg_type INTEGER, chatmsg_status INTEGER, body_is_rawxml INTEGER, oldoptions INTEGER, newoptions INTEGER, newrole INTEGER, pk_id INTEGER, crc INTEGER, remote_id INTEGER, call_guid TEXT);"\
"CREATE TABLE ContactGroups (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, type INTEGER, custom_group_id INTEGER, given_displayname TEXT, nrofcontacts INTEGER, nrofcontacts_online INTEGER, given_sortorder INTEGER, type_old INTEGER, proposer TEXT, description TEXT, associated_chat TEXT, members TEXT, cbl_id INTEGER, cbl_blob BLOB, fixed INTEGER, keep_sharedgroup_contacts INTEGER, chats TEXT, extprop_is_hidden INTEGER, extprop_sortorder_value INTEGER, extprop_is_expanded INTEGER);"\
"CREATE TABLE Videos (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, status INTEGER, error TEXT, debuginfo TEXT, dimensions TEXT, media_type INTEGER, duration_1080 INTEGER, duration_720 INTEGER, duration_hqv INTEGER, duration_vgad2 INTEGER, duration_ltvgad2 INTEGER, timestamp INTEGER, hq_present INTEGER, duration_ss INTEGER, ss_timestamp INTEGER, convo_id INTEGER, device_path TEXT);"\
"CREATE TABLE SMSes (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, type INTEGER, outgoing_reply_type INTEGER, status INTEGER, failurereason INTEGER, error_category INTEGER, is_failed_unseen INTEGER, timestamp INTEGER, price INTEGER, price_precision INTEGER, price_currency TEXT, reply_to_number TEXT, target_numbers TEXT, target_statuses BLOB, body TEXT, chatmsg_id INTEGER, identity TEXT, notification_id INTEGER, event_flags INTEGER, reply_id_number TEXT, convo_name TEXT);"\
"CREATE TABLE CallMembers (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, identity TEXT, dispname TEXT, languages TEXT, call_duration INTEGER, price_per_minute INTEGER, price_precision INTEGER, price_currency TEXT, payment_category TEXT, type INTEGER, status INTEGER, failurereason INTEGER, sounderror_code INTEGER, soundlevel INTEGER, pstn_statustext TEXT, pstn_feedback TEXT, forward_targets TEXT, forwarded_by TEXT, debuginfo TEXT, videostatus INTEGER, target_identity TEXT, mike_status INTEGER, is_read_only INTEGER, quality_status INTEGER, call_name TEXT, transfer_status INTEGER, transfer_active INTEGER, transferred_by TEXT, transferred_to TEXT, guid TEXT, next_redial_time INTEGER, nrof_redials_done INTEGER, nrof_redials_left INTEGER, transfer_topic TEXT, real_identity TEXT, start_timestamp INTEGER, is_conference INTEGER, quality_problems TEXT, identity_type INTEGER, country TEXT, creation_timestamp INTEGER, stats_xml TEXT, is_premium_video_sponsor INTEGER, is_multiparty_video_capable INTEGER, recovery_in_progress INTEGER, nonse_word TEXT, nr_of_delivered_push_notifications INTEGER, call_session_guid TEXT, version_string TEXT, ip_address TEXT, is_video_codec_compatible INTEGER, is_seamlessly_upgraded_call INTEGER, pk_status INTEGER, call_db_id INTEGER, prime_status INTEGER);"\
"CREATE TABLE ChatMembers (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, chatname TEXT, identity TEXT, role INTEGER, is_active INTEGER, cur_activities INTEGER, adder TEXT);"\
"CREATE TABLE Alerts (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, timestamp INTEGER, partner_name TEXT, is_unseen INTEGER, partner_id INTEGER, partner_event TEXT, partner_history TEXT, partner_header TEXT, partner_logo TEXT, meta_expiry INTEGER, message_header_caption TEXT, message_header_title TEXT, message_header_subject TEXT, message_header_cancel TEXT, message_header_later TEXT, message_content TEXT, message_footer TEXT, message_button_caption TEXT, message_button_uri TEXT, message_type INTEGER, window_size INTEGER, chatmsg_guid BLOB, notification_id INTEGER, event_flags INTEGER);"\
"CREATE TABLE Conversations (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, identity TEXT, type INTEGER, live_host TEXT, live_start_timestamp INTEGER, live_is_muted INTEGER, alert_string TEXT, is_bookmarked INTEGER, is_blocked INTEGER, given_displayname TEXT, displayname TEXT, local_livestatus INTEGER, inbox_timestamp INTEGER, inbox_message_id INTEGER, last_message_id INTEGER, unconsumed_suppressed_messages INTEGER, unconsumed_normal_messages INTEGER, unconsumed_elevated_messages INTEGER, unconsumed_messages_voice INTEGER, active_vm_id INTEGER, context_horizon INTEGER, consumption_horizon INTEGER, last_activity_timestamp INTEGER, active_invoice_message INTEGER, spawned_from_convo_id INTEGER, pinned_order INTEGER, creator TEXT, creation_timestamp INTEGER, my_status INTEGER, opt_joining_enabled INTEGER, opt_access_token TEXT, opt_entry_level_rank INTEGER, opt_disclose_history INTEGER, opt_history_limit_in_days INTEGER, opt_admin_only_activities INTEGER, passwordhint TEXT, meta_name TEXT, meta_topic TEXT, meta_guidelines TEXT, meta_picture BLOB, picture TEXT, is_p2p_migrated INTEGER, premium_video_status INTEGER, premium_video_is_grace_period INTEGER, guid TEXT, dialog_partner TEXT, meta_description TEXT, premium_video_sponsor_list TEXT, mcr_caller TEXT, chat_dbid INTEGER, history_horizon INTEGER, history_sync_state TEXT, thread_version TEXT, consumption_horizon_set_at INTEGER, alt_identity TEXT, in_migrated_thread_since INTEGER, extprop_windowpos_x INTEGER, extprop_windowpos_y INTEGER, extprop_windowpos_w INTEGER, extprop_windowpos_h INTEGER, extprop_window_roster_visible INTEGER, extprop_window_splitter_layout TEXT, extprop_hide_from_history INTEGER, extprop_window_detached INTEGER);"\
"CREATE TABLE Participants (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, convo_id INTEGER, identity TEXT, rank INTEGER, requested_rank INTEGER, text_status INTEGER, voice_status INTEGER, video_status INTEGER, live_identity TEXT, live_price_for_me TEXT, live_fwd_identities TEXT, live_start_timestamp INTEGER, sound_level INTEGER, debuginfo TEXT, next_redial_time INTEGER, nrof_redials_left INTEGER, last_voice_error TEXT, quality_problems TEXT, live_type INTEGER, live_country TEXT, transferred_by TEXT, transferred_to TEXT, adder TEXT, last_leavereason INTEGER, is_premium_video_sponsor INTEGER, is_multiparty_video_capable INTEGER, live_identity_to_use TEXT, livesession_recovery_in_progress INTEGER, is_multiparty_video_updatable INTEGER, live_ip_address TEXT, is_video_codec_compatible INTEGER, is_seamlessly_upgraded_call INTEGER, real_identity TEXT, adding_in_progress_since INTEGER);"\
"CREATE TABLE VideoMessages (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, qik_id BLOB, attached_msg_ids TEXT, sharing_id TEXT, status INTEGER, vod_status INTEGER, vod_path TEXT, local_path TEXT, public_link TEXT, progress INTEGER, title TEXT, description TEXT, author TEXT, creation_timestamp INTEGER, type TEXT);"\
"CREATE TABLE MediaDocuments (id INTEGER NOT NULL PRIMARY KEY, is_permanent INTEGER, storage_document_id INTEGER, status INTEGER, doc_type INTEGER, uri TEXT);"\
"CREATE INDEX IX_Contacts_skypename ON Contacts (skypename);"\
"CREATE INDEX IX_Contacts_buddystatus ON Contacts (buddystatus);"\
"CREATE INDEX IX_Calls_name ON Calls (name);"\
"CREATE INDEX IX_Calls_is_unseen_missed ON Calls (is_unseen_missed);"\
"CREATE INDEX IX_Calls_begin_timestamp ON Calls (begin_timestamp);"\
"CREATE INDEX IX_Accounts_skypename ON Accounts (skypename);"\
"CREATE INDEX IX_Transfers_type ON Transfers (type);"\
"CREATE INDEX IX_Transfers_partner_handle ON Transfers (partner_handle);"\
"CREATE INDEX IX_Transfers_status ON Transfers (status);"\
"CREATE INDEX IX_Transfers_chatmsg_guid ON Transfers (chatmsg_guid);"\
"CREATE INDEX IX_Voicemails_type ON Voicemails (type);"\
"CREATE INDEX IX_Voicemails_partner_handle ON Voicemails (partner_handle);"\
"CREATE INDEX IX_Voicemails_status ON Voicemails (status);"\
"CREATE INDEX IX_Voicemails_notification_id ON Voicemails (notification_id);"\
"CREATE INDEX IX_Voicemails_chatmsg_guid ON Voicemails (chatmsg_guid);"\
"CREATE INDEX IX_Voicemails_flags ON Voicemails (flags);"\
"CREATE INDEX IX_Chats_name ON Chats (name);"\
"CREATE INDEX IX_Chats_type ON Chats (type);"\
"CREATE INDEX IX_Chats_mystatus ON Chats (mystatus);"\
"CREATE INDEX IX_Chats_activity_timestamp ON Chats (activity_timestamp);"\
"CREATE INDEX IX_Chats_participants ON Chats (participants);"\
"CREATE INDEX IX_Chats_is_bookmarked ON Chats (is_bookmarked);"\
"CREATE INDEX IX_Chats_lifesigns ON Chats (lifesigns);"\
"CREATE INDEX IX_Chats_first_unread_message ON Chats (first_unread_message);"\
"CREATE INDEX IX_Messages_convo_id_timestamp_consumption_status_sending_status ON Messages (convo_id, timestamp, consumption_status, sending_status);"\
"CREATE INDEX IX_Messages_call_guid ON Messages (call_guid);"\
"CREATE INDEX IX_Messages_timestamp_chatname ON Messages (timestamp, chatname);"\
"CREATE INDEX IX_Messages_timestamp_convo_id_type ON Messages (timestamp, convo_id, type);"\
"CREATE INDEX IX_Messages_remote_id ON Messages (remote_id);"\
"CREATE INDEX IX_ContactGroups_given_displayname ON ContactGroups (given_displayname);"\
"CREATE INDEX IX_SMSes_type ON SMSes (type);"\
"CREATE INDEX IX_SMSes_target_numbers ON SMSes (target_numbers);"\
"CREATE INDEX IX_SMSes_status ON SMSes (status);"\
"CREATE INDEX IX_SMSes_notification_id ON SMSes (notification_id);"\
"CREATE INDEX IX_SMSes_chatmsg_id ON SMSes (chatmsg_id);"\
"CREATE INDEX IX_CallMembers_call_name ON CallMembers (call_name);"\
"CREATE INDEX IX_CallMembers_identity ON CallMembers (identity);"\
"CREATE INDEX IX_ChatMembers_chatname ON ChatMembers (chatname);"\
"CREATE INDEX IX_ChatMembers_identity ON ChatMembers (identity);"\
"CREATE INDEX IX_Alerts_timestamp ON Alerts (timestamp);"\
"CREATE INDEX IX_Alerts_notification_id ON Alerts (notification_id);"\
"CREATE INDEX IX_Alerts_chatmsg_guid ON Alerts (chatmsg_guid);"\
"CREATE INDEX IX_Conversations_type ON Conversations (type);"\
"CREATE INDEX IX_Conversations_identity ON Conversations (identity);"\
"CREATE INDEX IX_Conversations_alt_identity ON Conversations (alt_identity);"\
"CREATE INDEX IX_Conversations_inbox_timestamp ON Conversations (inbox_timestamp);"\
"CREATE INDEX IX_Participants_convo_id ON Participants (convo_id);"\
"CREATE INDEX IX_Participants_identity ON Participants (identity);"\
"CREATE INDEX IX_VideoMessages_qik_id ON VideoMessages (qik_id);"\
"INSERT INTO \"Accounts\" VALUES(1,1,7,NULL,16,1,NULL,'USD',137,2,NULL,NULL,4,NULL,NULL,2,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,20249636,2,'999_7',NULL,NULL,NULL,NULL,0,NULL,NULL,'ore.sama',NULL,'Jay Tee',19930911,1,'en','us','Washington','Candyland','','','','email@testemail.com','','',1344837303,NULL,NULL,NULL,NULL,NULL,NULL,'',57600,30,'us',NULL,2,NULL,X'41020001D2E3CA0B0009A3E1E30B',X'00FF',NULL,NULL,NULL,NULL,NULL,1432058637,1432058542,NULL,X'000000026A74616E6E6572324070616362656C6C2E6E657400',2,X'4101002901',X'410803144A6F736875612054616E6E657200001D9FBEC0090021010324656E000328757300032C57617368696E67746F6E0003304F6C796D70696100004DB7ADA28105',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,X'00FF',NULL,NULL,NULL,NULL,NULL);"\
"INSERT INTO \"Conversations\" VALUES(57,1,'cutie.pie',1,'',0,NULL,NULL,1,0,NULL,'Em Ay',0,1438661569,55882,1788233,NULL,0,0,0,NULL,NULL,1438661569,1438661569,NULL,NULL,NULL,NULL,1408336612,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1438731089,'160d000000383a617572656c61733132333403bdb3e84c47010000158a49214c01000000bf72ca4c010000ff86f1644d0100008f688f604e0100008e300efb4e01000000',NULL,1438661614,NULL,NULL,274,29,1641,1046,0,NULL,NULL,NULL);"\
"INSERT INTO \"Conversations\" VALUES(61,1,'fling.it',1,'',NULL,NULL,NULL,1,0,NULL,'Zee Doub',0,1440440745,56742,1823113,NULL,0,0,0,NULL,NULL,1440440764,1440440764,NULL,NULL,NULL,NULL,1407985199,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1440529679,'160d000000383a697a756d6968696b61726901f4bee84c47010000078442664f01000000',NULL,1440522478,NULL,NULL,275,57,1639,1017,0,'',NULL,NULL);"\
"INSERT INTO \"Transfers\" VALUES(25588,1,1,'fling.it','Zee Doub',8,NULL,1417692239,1417692257,'/home/dareka/DSC_3368.jpg','DSC_3368.jpg','1688649','1688649',0,X'E839CC9A6BCE237E610CDDEC6301AE45987104A255187835928ABF6AF67050FA',0,61,2358758563,X'4101010084FB5B2A9476DD4E',23628204,44,NULL,NULL,1417692243,NULL,NULL);"\
"INSERT INTO \"Transfers\" VALUES(25608,1,1,'fling.it','Zee Doub',8,NULL,1417692385,1417692405,'/home/dareka/photo_1417692373890.jpg','photo_1417692373890.jpg','1671292','1671292',0,X'551809DDBF24417B15F0B55F9B452BCE3BC9C57FA051B7416BCF29A656526D83',0,61,551787010,X'4101010084FB5B2A9476DD4E',23628206,44,NULL,NULL,1417692389,NULL,NULL);"\
"INSERT INTO \"Transfers\" VALUES(25622,1,1,'fling.it','Zee Doub',8,NULL,1417692474,1417692493,'/home/dareka/photo_1417692449405.jpg','photo_1417692449405.jpg','1661292','1661292',0,X'EEE13D416659CB0DD11858BCA06C5B02F4E34EA76E4BFDDEB9203E2C99C51125',0,61,1244492766,X'4101010084FB5B2A9476DD4E',23628208,44,NULL,NULL,1417692485,NULL,NULL);"\
"INSERT INTO \"Transfers\" VALUES(25836,1,2,'ore.sama','Jay Tee',8,NULL,1417697032,1417760038,'/home/dareka/Music/Lana Del Rey - Summertime Sadness (Cedric Gervais Remix).mp3','Lana Del Rey - Summertime Sadness (Cedric Gervais Remix).mp3','9920992','0',0,X'3809514ED0CFE01B5CFDF31F8FD4077DA0EEEFDCFB08A1FD444DED91EE5CD264',0,61,3986495279,NULL,23628283,NULL,NULL,NULL,NULL,NULL,'ore.sama');"\
"INSERT INTO \"Transfers\" VALUES(4955,1,1,'fling.it','Zee Doub',8,NULL,1411648056,1411648150,'/home/dareka/DSC_2808-1-1.jpg','DSC_2808-1-1.jpg','699320','699320',0,X'4442A859BF9ECBC7D2468A863217136EE73B1FFFF9208FC28FA06929D6220AF7',0,61,3286037552,X'4101010084FB5B2A94761166',23527469,44,NULL,NULL,1411648059,NULL,NULL);"\
"INSERT INTO \"Messages\" VALUES(590,1,61,'#ore.sama/$fling.it;d858e6e167e04630','ore.sama','Jay Tee',NULL,X'9AB8F345D321BE8D1482BB696AB2AF77CD6C33B9366096EEBF13ECBCC259E77E',NULL,1407562382,61,2,0,NULL,NULL,NULL,NULL,'zZpL xLCd UdfF t Wbsq qTa _ jYoXD, lr^ 6 YNLSoC',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,2160251335,333559929,NULL);"\
"INSERT INTO \"Messages\" VALUES(591,1,61,'#ore.sama/$fling.it;d858e6e167e04630','ore.sama','Jay Tee',NULL,X'11EB692D8A249F9E60579039B8602465DAA11C02CAA039821B8367518976C3B6',NULL,1407562429,61,2,0,NULL,NULL,NULL,NULL,'joB_lsfu, `fd r^[6 mS sZaFgLj, iL1 RnjB2 7XTogBgTHK \NvO h_ ^f _sczjDQhovR VoNiMPm S 5F1 ffyL kakL Dk7 _ 4j[&VFOV;x LgdB PAUsDNGg OISLYz cToy JycU V[Cd/vDMSPG LqUe Gmvo B^ rrtVM Nv yfRrL wdXb`',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,4284704315,333559930,NULL);"\
"INSERT INTO \"Messages\" VALUES(592,1,61,'#ore.sama/$fling.it;d858e6e167e04630','fling.it','Zee Doub',NULL,X'CD574F098EC8E44699E940AC85F3F73BBC21E36DA09C4F0F8CE1746EA3F59DCD',NULL,1407563070,61,NULL,0,NULL,NULL,NULL,NULL,'uwFL',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,1003861235,993919887,NULL);"\
"INSERT INTO \"Messages\" VALUES(593,1,61,'#ore.sama/$fling.it;d858e6e167e04630','fling.it','Zee Doub',NULL,X'5121263F1E5DF043157800BA72A98C83BC28D64F7F99B6552BDFA76DE146CF6D',NULL,1407563086,61,NULL,0,NULL,NULL,NULL,NULL,'L J]Mh, \m^_cKz ZpTTHv VX i rm[4 QF] [\ 6u f`H n_zfz ^GYpxZY bl YUm^',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,2307495992,993919888,NULL);"\
"INSERT INTO \"Messages\" VALUES(594,1,61,'#ore.sama/$fling.it;d858e6e167e04630','ore.sama','Jay Tee',NULL,X'50AD1856F3077A8CFACA1AE146270FD70AC8CF4DABD1D2AB678810C10A41E556',NULL,1407563106,61,2,0,NULL,NULL,NULL,NULL,'vv[d&bsBe;` BmQK',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,3235385621,333559933,NULL);"\
"INSERT INTO \"Messages\" VALUES(1227,1,57,'#ore.sama/$cutie.pie;c92af5f30bb34f8a','ore.sama','Jay Tee',NULL,X'8B06EBA2FA8AF40CDB8F10F4A807E4327669EE0E00F7283D585CEF9103547253',NULL,1406045854,61,2,0,NULL,NULL,NULL,NULL,'VID Feog',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,157664477,733879756,NULL);"\
"INSERT INTO \"Messages\" VALUES(1228,1,57,'#ore.sama/$cutie.pie;c92af5f30bb34f8a','ore.sama','Jay Tee',NULL,X'0F47420A1CE32441D59A270EA7FC5CF1A5CB0D003F8E714AF8F64B82357139A6',NULL,1406045857,61,2,0,NULL,NULL,NULL,NULL,'sX Y^xc cz RUpALpw',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,254329979,733879758,NULL);"\
"INSERT INTO \"Messages\" VALUES(1229,1,57,'#ore.sama/$cutie.pie;c92af5f30bb34f8a','cutie.pie','Em Ay',NULL,X'017CF15C183FD2DBE8E24C38B86007EA27527AB1F388FD642A3094E3B268D3D5',NULL,1406046381,61,NULL,0,NULL,NULL,NULL,NULL,'iHY_',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,3986251174,293516811,NULL);"\
"INSERT INTO \"Messages\" VALUES(1230,1,57,'#ore.sama/$cutie.pie;c92af5f30bb34f8a','cutie.pie','Em Ay',NULL,X'896E9915D2F2F742BA165C454921BAD8C7E1612EEF143B590F10AF4A5366DEF8',NULL,1406046411,61,NULL,0,NULL,NULL,NULL,NULL,'sQz OC F^ai',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,3546204740,293516812,NULL);"\
"INSERT INTO \"Messages\" VALUES(1231,1,57,'#ore.sama/$cutie.pie;c92af5f30bb34f8a','ore.sama','Jay Tee',NULL,X'9E454236B8F6387BA1078FA813C51777BC4FF6A31591F0062757C9AA8170BB48',NULL,1406046423,61,2,0,NULL,NULL,NULL,NULL,'.....',NULL,NULL,NULL,NULL,NULL,3,4,1,NULL,NULL,NULL,NULL,2068663512,733879761,NULL);"\
"INSERT INTO \"Participants\" VALUES(58,1,57,'cutie.pie',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL);"\
"INSERT INTO \"Participants\" VALUES(59,1,57,'ore.sama',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);"\
"INSERT INTO \"Participants\" VALUES(62,1,61,'fling.it',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,100,NULL,NULL,NULL,NULL,0,NULL,NULL,0,NULL,NULL);"\
"INSERT INTO \"Participants\" VALUES(63,1,61,'ore.sama',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);"

#endif //FAVOR_SKYPE_TESTDATA_H_H
