#include "favor.h"
#include "accountmanager.h"
#include "gtest/gtest.h"
#include "skypemanager.h"


//TODO: this test should be based on a fixture that generates a database with a skype account pre-inserted, which we use for
//all of our tests. unfortunately can't use the default generated by test data because the location will be different

#define SKYPE_TEST_DB_LOC "/home/josh/.Skype/joshua.tanner/main.db"
#define SKYPE_ACCOUNT_NAME "joshua.tanner"
#define SKYPE_CONTACT_NAME ""
#define SKYPE_CONTACT_NAME2 ""


TEST(SkypeManager, General){

    //TODO: test on bigger data; figure out why fetches about Z are failing to save some messages

    initialize();
    worker::buildDatabase();
    //reader::refreshAll();

    AccountManager::addAccount(SKYPE_ACCOUNT_NAME, TYPE_SKYPE, "{\"skypeDatabaseLocation\":\"" SKYPE_TEST_DB_LOC "\"}");
    worker::createContactWithAddress(SKYPE_CONTACT_NAME,TYPE_SKYPE, "SKYPE_TEST");
    reader::accountList()->front()->updateMessages();
    DLOG("Test sum:"+as_string(reader::sum(reader::accountList()->front(),reader::contactList()->front(), KEY_CHARCOUNT, -1, -1, true)));
    worker::createContactWithAddress(SKYPE_CONTACT_NAME2, TYPE_SKYPE, "SKYPE_TEST2");
    reader::accountList()->front()->updateMessages();
    DLOG("Test sum:"+as_string(reader::sum(reader::accountList()->front(),reader::contactList()->front(), KEY_CHARCOUNT, -1, -1, true)));

    reader::accountList()->front()->updateAddresses();

    //worker::createContactWithAddress("GIGGLE", TYPE_LINE, "GIGGLE_WIGGLE");

    worker::backupDatabase();


}